# File: .readthedocs.yaml

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# Explicitly set the version of Python and its requirements
python:
  version: "3.8"
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py